Optimizes session responses
RebelCode/rcmod-eddbk-rest-api pull request #12
Opened 2018-05-22 11:32 UTC by mecha

Resolves #11

2018-05-23 15:25 UTC, XedinUnknown requested changes

2018-05-23 15:25 UTC, XedinUnknown commented on src/Controller/SessionsController.php
> +    const DEFAULT_NUM_ITEMS_PER_PAGE = 500;
This should come from configuration. In the future, we can let the admin change this using the GUI.

2018-05-23 15:25 UTC, XedinUnknown commented on src/Module/EddBkRestApiModule.php
> +                        $c->get('sql_order_factory')->make([
In the future, when order objects have their own factories, new constants should be used for keys.
https://github.com/Dhii/sql-interface/issues/9

2018-05-23 15:28 UTC, XedinUnknown commented on src/Module/EddBkRestApiModule.php
> -                            MapTransformer::K_TRANSFORMER => $c->get('eddbk_rest_api_service_id_transformer'),
Optimisation is mainly achieved by removing this transformer, which included service details with each session.

2018-05-24 11:37 UTC, mecha commented on src/Module/EddBkRestApiModule.php
> -                            MapTransformer::K_TRANSFORMER => $c->get('eddbk_rest_api_service_id_transformer'),
Is this a review, comment or just a statement?

2018-05-24 11:38 UTC, mecha commented on src/Controller/SessionsController.php
> +    const DEFAULT_NUM_ITEMS_PER_PAGE = 500;
Correct. I will make amends.

2018-05-24 14:10 UTC, XedinUnknown commented on src/Module/EddBkRestApiModule.php
> -                            MapTransformer::K_TRANSFORMER => $c->get('eddbk_rest_api_service_id_transformer'),
Just a comment to clarify.

2018-05-24 14:11 UTC, XedinUnknown approved these changes
Amazing. A breath of fresh air.

2018-05-24 14:11 UTC, merged